project_id = "kypvowwxewqkpcjcivbf"

[functions.analyze-documents]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.analyze-response]
verify_jwt = false

[functions.extract-relevant-resume]
verify_jwt = false